### ISSUE TITLE
秘密トークン

### ISSUE THREAD

**Issue by katorie** [katorie/rss_reader#48]
チュートリアルでやったけど、よくわからなかった。

**Comment by 5t111111** [comment]
Rails 4.1 にアップデートしてるから `config/initializers/secret_token.rb` は要らないのでファイルを削除していいと思います。(自分も今日このことを知って削除した。)

Rails 4.1 から、秘密トークンの情報は `config/secrets.yml` に持つようになってます。で、その中身見れば分かる通り、

```ruby
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```

となっているので、production 環境では環境変数 `SECRET_KEY_BASE` の値が設定されるようになっています。しかもこれ、Heroku にデプロイすると、Heroku 側で自動的にこの環境変数 `SECRET_KEY_BASE` を設定してくれるようになってるので、他のことは何もせず、単純に  `config/initializers/secret_token.rb` を消せばOKです。

知ってると思うけど一応、この秘密トークンというのは、セッションの情報を暗号化するために使われるキーです。Railsはデフォルトではセッションのデータをサーバーに持たず、クライアントのCookieがすべてセッション情報を持つので、その情報を解析してセッションを乗っ取られたりしないように、こういった秘密のキーをサーバー側に持ってて、それがないと復号できないようにしてるんですね。

なのでこのキーは本来、ぜったいに秘密にしておかないといけないものです。Rails チュートリアルは 4.0 が対象で、まだ `config/secrets.yml` もなかった頃のことなので、 `config/initializers/secret_token.rb`  に直接書かず、動的に生成するように変更してたというわけです。コードに直接書かれたままだと、こうやって Github でなどで公開したときにキーが流出してしまうので。

**Comment by katorie** [comment]
@5t111111 ありがとうございます！！丁寧な解説たすかります :bow: 
セキュリティのこと、全然理解が足りてない感じなので、勉強しようと思います。
とりあえず`config/initializers/secret_token.rb`は削除します！！
